### ISSUE TITLE
sql names

### ISSUE THREAD

**Issue by vitaly-t** [tcandens/cranesOfSeattle#2]
```js
UPDATE ${this.tableName} SET $/key^/ = $/value/ WHERE id = $/id/
```
Instead of using raw-text variables, use [SQL Names](https://github.com/vitaly-t/pg-promise#sql-names) syntax:
```js
UPDATE ${this.tableName} SET $/key~/ = $/value/ WHERE id = $/id/
```

It is much safer this way, plus:

>Relying on this type of formatting for sql names and identifiers, along with regular variable formatting makes your application impervious to sql injection.

**Comment by tcandens** [comment]
Thanks,  @vitaly-t! I definitely appreciate the note and all your work with pg-promise.

**Comment by vitaly-t** [comment]
You are welcome! Some of the changes you made though look wrong, like this one:
```js
SELECT * FROM ${this.tableName} WHERE id = $1~
```
I take it `id` expects a value, i.e. `$1`, not an SQL Identifier.

**Comment by vitaly-t** [comment]
Similar to that...
```js
'POINT($/lng~/ $/lat~/)', $/radius~/
```
These are values, they are not SQL Names :)

**Comment by tcandens** [comment]
I've changed some fixes per your suggestions. Again, appreciated!
